export const errorTypes = {
  INVALID_AUTHENTICATION: 'INVALID_AUTHENTICATION',
  API_KEY_NOT_FOUND: 'API_KEY_NOT_FOUND',

  BUSINESS_ID_IS_NEEDED: 'BUSINESS_ID_IS_NEEDED',

  DATABASE_WRITE_ERROR: 'DATABASE_WRITE_ERROR',
  DATABASE_READ_ERROR: 'DATABASE_READ_ERROR',
}
