export const errorTypes = {
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  SLUG_ALREADY_EXISTS: 'SLUG_ALREADY_EXISTS',
  BUSINESS_NOT_FOUND: 'BUSINESS_NOT_FOUND',

  DATABASE_WRITE_ERROR: 'DATABASE_WRITE_ERROR',
  DATABASE_READ_ERROR: 'DATABASE_READ_ERROR',

  HASH_ERROR: 'ERROR_ON_HASH_GENERATION',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
}
