export const errorTypes = {
  STAFF_EMAIL_ALREADY_EXISTS_IN_BUSINESS: 'STAFF_EMAIL_ALREADY_EXISTS_IN_BUSINESS',
  STAFF_DOES_NOT_EXISTS: 'STAFF_DOES_NOT_EXISTS',

  SERVICE_NAME_ALREADY_EXISTS: 'SERVICE_NAME_ALREADY_EXISTS_IN_THIS_BUSINESS',
  SERVICE_DOES_NOT_EXISTS: 'SERVICE_DOES_NOT_EXISTS',

  TIME_OFF_INTERFER_WITH_ANOTHER: 'TIME_OFF_INTERFER_WITH_ANOTHER',
  TIME_OFF_DOES_NOT_EXISTS: 'TIME_OFF_DOES_NOT_EXISTS',

  AGENDA_FOR_THIS_STAFF_ALREADY_EXISTS: 'AGENDA_FOR_THIS_STAFF_ALREADY_EXISTS',
  AGENDA_DOES_NOT_EXISTS: 'AGENDA_OFF_DOES_NOT_EXISTS',

  INVALID_TIMEZONE: (tz: string) => `INVALID_TIMEZONE -> ${tz}`,
  INVALID_DATE_FORMAT: 'INVALID_DATE_FORMAT',

  DATABASE_READ_ERROR: 'DATABASE_READ_ERROR',
  DATABASE_WRITE_ERROR: 'DATABASE_WRITE_ERROR',
  DATABASE_DELETE_ERROR: 'DATABASE_DELETE_ERROR',
}
